site_name: "[DEV] Engineering Collaboration"
site_author: Daniel Lanner
site_url: https://engineering-collaboration.io/
site_description: >-
  Engineering Collaboration presents a vertical slice of strategies 
  that have proven useful for a broad spectrum of organizations. This brief literary 
  excursion provides the foundation for building an autonomous, flexible, and 
  collaborative environment at the core of our company.

copyright: Written by <a href="https://daniellanner.io" target="_blank">Daniel Lanner</a>

repo_url: https://github.com/engineering-collaboration/book
repo_name: engineering-collaboration/book
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: src/overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/github 

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: custom
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - header.autohide
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - navigation.tabs
    - search.suggest
    - search.highlight
    - search.share

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/daniellanner/
    - icon: fontawesome/brands/github 
      link: https://github.com/daniellanner
    - icon: fontawesome/solid/globe
      link: https://daniellanner.io

extra_css:
  - assets/extra.css

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Home:
    - 'index.md'
  - Book:
    - './book/README.md'
    - DevOps, Agile, and Lean: './book/devops-agile-lean.md'

    - Collaborating within a Company:
      - './book/collaborating-within-a-company/README.md'
      - Autonomous Team Structure: './book/collaborating-within-a-company/autonomous-team-structure.md'
      - Team Interactions: './book/collaborating-within-a-company/team-interactions.md'
      - Communication Channels: './book/collaborating-within-a-company/communication-channels.md'
      - Working in Cycles: './book/collaborating-within-a-company/working-in-cycles.md'
      - Innersourcing: './book/collaborating-within-a-company/innersourcing.md'
      - Team Education and Training: './book/collaborating-within-a-company/team-education-and-training.md'

    - Collaborating within a Codebase:
      - './book/collaborating-within-a-codebase/README.md'
      - CI/CD: './book/collaborating-within-a-codebase/cicd.md'
      - Trunk Based Development: './book/collaborating-within-a-codebase/trunk-based-development.md'
      - Planning Implementations: './book/collaborating-within-a-codebase/planning-implementations.md'
      - Commits: './book/collaborating-within-a-codebase/commits.md'
      - Pull Requests: './book/collaborating-within-a-codebase/pull-requests.md'
      - Static Analysis: './book/collaborating-within-a-codebase/static-analysis.md'
      - Code Reviews: './book/collaborating-within-a-codebase/code-review.md'
      - Merging: './book/collaborating-within-a-codebase/merging.md'

      - Testing:
        - './book/collaborating-within-a-codebase/testing/README.md'
        - Automated Functional Tests: './book/collaborating-within-a-codebase/testing/small-scoped-tests.md'
        - Beyond Functional Tests: './book/collaborating-within-a-codebase/testing/benchmark-tests.md'

      - Release Mechanisms: './book/collaborating-within-a-codebase/release-mechanisms.md'
      - Artifact Management: './book/collaborating-within-a-codebase/artifact-management.md'
      - Release Strategies: './book/collaborating-within-a-codebase/release-strategies.md'

      - Documentation: './book/collaborating-within-a-codebase/documentation.md'
      - Repository Strategies: './book/collaborating-within-a-codebase/repository-strategies.md'
      - Monitoring and Observability: './book/collaborating-within-a-codebase/monitoring-and-observability.md'

  - Resources: 'resources.md'
  - Changelog: 'changelog.md'
