site_name: "[DEV] The anatomy of collaboration in software"
site_author: Daniel Lanner
site_url: https://the-anatomy-of-collaboration.io/
site_description: >-
  The anatomy of collaboration in software presents a vertical slice of strategies 
  that have proven useful for a broad spectrum of organizations. This brief literary 
  excursion provides the foundation for building an autonomous, flexible, and 
  collaborative environment at the core of our company.

copyright: Written by <a href="https://daniellanner.io" target="_blank">Daniel Lanner</a>

repo_url: https://github.com/the-anatomy-of-collaboration/book
repo_name: the-anatomy-of-collaboration/book
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: src/overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/github 

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: custom
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - header.autohide
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - navigation.tabs

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/daniellanner/
    - icon: fontawesome/brands/github 
      link: https://github.com/daniellanner
    - icon: fontawesome/solid/globe
      link: https://daniellanner.io

extra_css:
  - assets/extra.css

plugins:
  - social:
      cards_layout_options:
        background_color: "#14151A"
        color: "#ffffff"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Home:
    - 'index.md'
  - Book:
    - Introduction:
      - './book/introduction/README.md'
      - Motivation: './book/introduction/motivation.md'
      - DevOps, Agile, Lean: './book/introduction/devops-agile-lean.md'
      - Blameless Culture: './book/introduction/blameless-culture.md'

    - The anatomy of a software company:
      - './book/anatomy-of-a-software-company/README.md'
      - An Enabling Organization: './book/anatomy-of-a-software-company/an-enabling-organization.md'
      - Autonomous team structure: './book/anatomy-of-a-software-company/autonomous-team-structure.md'
      - Internal Supporting Teams: './book/anatomy-of-a-software-company/internal-supporting-teams.md'
      - Communication Channels: './book/anatomy-of-a-software-company/communication-channels.md'
      - Team Interactions: './book/anatomy-of-a-software-company/team-interactions.md'
      - Standardization: './book/anatomy-of-a-software-company/standardization.md'
      - Innersourcing: './book/anatomy-of-a-software-company/innersourcing.md'
      - Team Education and Training: './book/anatomy-of-a-software-company/team-education-and-training.md'

    - The anatomy of managing a team:
      - './book/anatomy-of-managing-a-team/README.md'

    - The anatomy of a code change:
      - './book/anatomy-of-a-code-change/README.md'
      - CICD: './book/anatomy-of-a-code-change/cicd.md'
      - Planning Implementations: './book/anatomy-of-a-code-change/planning-implementations.md'
      - Trunk Based Development: './book/anatomy-of-a-code-change/trunk-based-development.md'
      - Commits: './book/anatomy-of-a-code-change/commits.md'
      - Pull Requests: './book/anatomy-of-a-code-change/pr.md'
      - Static Analyses: './book/anatomy-of-a-code-change/static-analyses.md'
      - Code Reviews: './book/anatomy-of-a-code-change/code-review.md'

      - Merging:
        - './book/anatomy-of-a-code-change/merge/README.md'
        - Merge Commit: './book/anatomy-of-a-code-change/merge/merge-commit.md'
        - Rebase: './book/anatomy-of-a-code-change/merge/rebase.md'
        - Squash: './book/anatomy-of-a-code-change/merge/squash.md'
        - Cherry Pick: './book/anatomy-of-a-code-change/merge/cherry-pick.md'
        - Summary: './book/anatomy-of-a-code-change/merge/summary.md'

      - Testing:
        - './book/anatomy-of-a-code-change/testing/README.md'
        - Good Practices: './book/anatomy-of-a-code-change/testing/good-practices.md'
        - Small Scoped Tests: './book/anatomy-of-a-code-change/testing/small-scoped-tests.md'
        - Medium Scoped Tests: './book/anatomy-of-a-code-change/testing/medium-scoped-tests.md'
        - Large Scoped Tests: './book/anatomy-of-a-code-change/testing/large-scoped-tests.md'
        - Benchmark Tests: './book/anatomy-of-a-code-change/testing/benchmark-tests.md'
        - Manual Tests: './book/anatomy-of-a-code-change/testing/manual-tests.md'
        - Testing in Production: './book/anatomy-of-a-code-change/testing/in-production.md'

      - Documentation:
        - Documentation: './book/anatomy-of-a-code-change/documentation/README.md'
        - Documentation in Code: './book/anatomy-of-a-code-change/documentation/inline.md'
        - Documentation for Disciplines: './book/anatomy-of-a-code-change/documentation/for-disciplines.md'

      - Release Mechanisms:
        - './book/anatomy-of-a-code-change/release-mechanism/README.md'
        - Tags: './book/anatomy-of-a-code-change/release-mechanism/tags.md'
        - Branches: './book/anatomy-of-a-code-change/release-mechanism/release-branches.md'
        - Live at Head: './book/anatomy-of-a-code-change/release-mechanism/live-at-head.md'
        - Hotfixes: './book/anatomy-of-a-code-change/release-mechanism/hotfix.md'

      - Artifact Management: './book/anatomy-of-a-code-change/artifact-management.md'
      - Release Strategies: './book/anatomy-of-a-code-change/release-strategies.md'
      - Repository Strategies: './book/anatomy-of-a-code-change/repo.md'
      - Infrastructure as Code: './book/anatomy-of-a-code-change/iac.md'
      - Monitoring and Observability: './book/anatomy-of-a-code-change/monitoring.md'

  - Resources: 'resources.md'
  - Changelog: 'changelog.md'
